language: python
python:
  - 3.5
  - 3.6
  - 3.7
before_install:
  - python --version
  - pip install -U pip
  - sudo add-apt-repository -y ppa:mc3man/trusty-media
  - sudo apt-get install -y ffmpeg
install:
  - pip install . # install packages
dist: xenial
services:
  - xvfb
script: python tests.py   # run tests
